default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: oneline_development

test:
  <<: *default
  database: _test

production:
  url: <%= ENV['DATABASE_URL'] %>
  <<: *default
